name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
    paths:
      - "gesture_detect_app/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: gesture_detect_app

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --project gesturedetectai
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GESTUREDETECTAI }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service-account.json

      - name: Create Service Account File
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GESTUREDETECTAI }}' > ${{ github.workspace }}/service-account.json